baseURL = "http://pruhnuhv.github.io/"
languageCode = "en-us"
title = "pranav"
theme = "manis"

pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 5

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]

#	[[menu.main]]
#		name = "Blog"
#		url = "/post/"

	[[menu.main]]
		name = "About"
		url = "/about"
	
	[[menu.main]]
		name = "GSoC"
		url = "/gsoc"

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []
	
	# Site meta description
	description = "pranav's personal website."
	# Site's Tagline (Subtitle or Keyword)
	tagline = "he/him"
	# If true give attribution to this theme
	themeAttrib = true
	# URL to license file, can be outside of your domain
	licenseURL = "/about/license"

	# Configure which sections for Latest Posts
	mainSections = ["blog", "post","gsoc"]
	# Configure which sections for Latest Works
	workSections = ["work"]
	
	# List of sections that support disqus comments
	disqusSections = [ "blog" ]
	# List of sections that support utterances comments
	utterancesSections = [ "blog" ]
	
	# Utterances Configuration
	utterancesRepo = ""
	utterancesTheme = "github-light"
	utterancesLabel = ""

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#ff6565"
	# Maximum number of item in Latest Posts or Works
	latestCount = 4
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "dangipranav@gmail.com"
	github = "https://github.com/pruhnuhv/"
	twitter = "https://twitter.com/willkwordyou"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

